Sprint 2/step 2
AlexanderIlinykhDev/react-burger pull request #6
Opened 2021-12-09 20:24 UTC by AlexanderIlinykhDev

2021-12-10 05:32 UTC, grishbar requested changes
Отличная работа проделана, круто, что воспользовался библиотекой immutability-helper, для избежания мутирования данных, классно, что везде написал усилители когда делаешь запросы, в целом весь функионал приложения работает корректно, есть некоторые моменты, которые нужно исправить, чтобы принять работу:

- [ ] Надо избавиться от дублирования кода
- [ ] Добавить catch при запросах
- [ ] Исправить подсчет цены заказа
- [ ] Возвращать дефолтное состояние хранилища при ошибке в запросе

Удачи в рефакторинге

2021-12-10 05:32 UTC, grishbar commented on src/components/app/app.jsx
> +const ENDPOINT = "https://norma.nomoreparties.space";
`надо исправить`
дублируешь ENDPOINT в  трех местах в проекте, и еще ее прокидывешь в компоненты,  вынеси эту константу в отдельный файл constants в src/utils и импортируй ее оттуда

2021-12-10 05:32 UTC, grishbar commented on src/components/burger-constructor-element/burger-constructor-element.jsx
> +      <div className={draggingElementClassName} ref={ref} key={index + 2}>
`надо исправить`
кажется одна из пропсов ref лишняя

2021-12-10 05:32 UTC, grishbar commented on src/components/burger-constructor-element/burger-constructor-element.jsx
> +          key={index + 3}
`можно лучше`
индексация по индексу [не круто](https://robinpokorny.medium.com/index-as-a-key-is-an-anti-pattern-e0349aece318), можно воспользоваться [uuid](https://www.npmjs.com/package/uuid)  тем боллее у тебя тут будут повторятся ключи, что совсем не очень, но по сути все должно работать корректно

2021-12-10 05:32 UTC, grishbar commented on src/components/burger-constructor-element/burger-constructor-element.module.css
> +}
`можно лучше`
постарайся выдерживать правильную идентацию в css

2021-12-10 05:32 UTC, grishbar commented on src/components/burger-constructor/burger-constructor.jsx
> +  const dispatch = useDispatch();
`можно лучше`
хуки лучше писать вначале компонента, так проще читать компонент

2021-12-10 05:32 UTC, grishbar commented on src/components/burger-constructor/burger-constructor.jsx
> +  function handleMakeOrderClick(event) {
`надо исправить`
переменные которые не используешь должны быть удалены (event)

2021-12-10 05:32 UTC, grishbar commented on src/components/burger-ingredients/burger-ingredients.jsx
> +  );
`надо исправить`
очень много дублирования кода, храни одно состояние, где будешь держать текущую активную ссылку ('bun' | 'fillings' | 'souses') и в зависимости от текущего состояния, выделяй активный элемент

2021-12-10 05:32 UTC, grishbar commented on src/components/burger-ingredients/burger-ingredients.jsx
> +  }
`надо исправить`
надо избавиться от дублирования кода, и в дефолтном состоянии у тебя тоже должна какая то ссылка подсвечиваться (первая)

2021-12-10 05:32 UTC, grishbar commented on src/components/burger-ingredients/burger-ingredients.jsx
> +    ) : (
`надо исправить`
вынеси это из useMemo и тернарник не понадобится
```
if (isLoading) {
      return (<p className="text text_type_main-large">Загрузка...</p>);
}
```

2021-12-10 05:32 UTC, grishbar commented on src/components/burger-ingredients/burger-ingredients.jsx
> +            </div>
`надо исправить`
дублируешь код три раза, вынеси это в отдельный компонент, к примеру можешь передавать в него тип и в зависимости от тиа фильтровать. выводить нужные компоненты и заголовок

2021-12-10 05:32 UTC, grishbar commented on src/components/burger-ingredients/burger-ingredients.jsx
> +      )}
`можно лучше`
будет лучше, если ты будешь хранить в redux данные текущего ингредиента показываемого в модалке

2021-12-10 05:32 UTC, grishbar commented on src/components/ingredient-card/ingredient-card.jsx
> +      (bun._id === props._id);
`можно лучше`
filter фильтрует элементы, а тебя исходя из массива надо посчитать какой то результат, тут семантически лучше подоходит reduce, воспользуйся им

2021-12-10 05:32 UTC, grishbar commented on src/services/actions/burger-constructor.js
> +};
`можно лучше`
на мой взгляд это все излишнее, выносить примитивные action в отдельную функцию не очень, и так когда будешь диспатчить экшен с его типом, будет понятно, за что он отвечает

2021-12-10 05:32 UTC, grishbar commented on src/services/actions/burger-constructor.js
> +      .then((data) => dispatch(getOrderNumberSuccess(data.order.number)));
`надо исправить`
тут также должен быть .catch потому что у тебя  может например body ответа быть невалидным json и все приложение развалится

2021-12-10 05:32 UTC, grishbar commented on src/services/reducers/burger-constructor.js
> +          };
`надо исправить`
условие в if не совсем понятно и излишнее, totalPrice лучше всегда пересчитывать исходя из ингредиентов, которые лежат сейчас в хранилище, а не добавлять динамически

2021-12-10 05:32 UTC, grishbar commented on src/services/reducers/burger-constructor.js
> +  }
`надо исправить`
это должно быть в отдельном файле

2021-12-10 05:32 UTC, grishbar commented on src/services/reducers/burger-constructor.js
> +    }
`надо исправить`
При ошибке в запросе надо возвращать - initialState и error: true , так как не хочется держать в хранилище потенциально невалидные данные

2021-12-10 05:32 UTC, grishbar commented on src/services/reducers/burger-ingredients.js
> +      return { ...state, error: true, loading: false };
`надо исправить`
тут также надо возвращать ingredientsInitialState и error: true,

2021-12-10 08:32 UTC, AlexanderIlinykhDev commented on src/components/burger-constructor-element/burger-constructor-element.module.css
> +}
Подскажите пожалуйста, что такое инетация?

2021-12-10 08:36 UTC, grishbar commented on src/components/burger-constructor-element/burger-constructor-element.module.css
> +}
привет, идентация это оступы, они должны быть везде одинаковые и согласно их вложенности, то есть вместо
```
.dpopTarget {
	display: flex;
  align-items: center;
  justify-content: center;
}
```
должно быть
```
.dpopTarget {
    display: flex;
    align-items: center;
    justify-content: center;
}
```

2021-12-10 14:23 UTC, grishbar requested changes
Обрати внимание, писал тебе про дублирование кода, от него надо избавиться, также вынеси логику подсчета суммы ингредиентов из jsx

2021-12-10 14:23 UTC, grishbar commented on src/components/burger-constructor/burger-constructor.jsx
> +              sausesAndFillings.map((chosenIngredient, index) => (
`можно лучше`
не обязательно проверять, что длинна ненулевая, так как map по пустому массиву ничего не вернет итак

2021-12-10 14:23 UTC, grishbar commented on src/components/burger-constructor/burger-constructor.jsx
> +                      .reduce((sum, price) => sum + price))}
`надо исправить`
вынеси это в компонент, в jsx не должно быть подсчетов, так как при каждом ререндере все будет пересчитываться и переменные создаваться заново, что негативно отражается на производительности, также отлично место, чтобы воспользоваться [useMemo](https://ru.reactjs.org/docs/hooks-reference.html#usememo)

2021-12-10 17:29 UTC, AlexanderIlinykhDev commented
@grishbar grishbar 12 hours ago
надо исправить
дублируешь ENDPOINT в трех местах в проекте, и еще ее прокидывешь в компоненты, вынеси эту константу в отдельный файл constants в src/utils и импортируй ее оттуда 
-------------->
Вроде дублирование уже исправил

2021-12-10 19:19 UTC, grishbar commented
Кажется, ты не заметил комментарии, вот здесь, если нажать кнопку loadmore, то появятся еще комментарии, там есть про дублирование ккода, которое хочу, чтобы ты исправил
<img width="893" alt="Screen Shot 2021-12-10 at 22 18 17" src="https://user-images.githubusercontent.com/32193933/145629568-2c9bbd13-4a5b-42e1-9adc-6e78dfdedb71.png">

2021-12-11 08:46 UTC, AlexanderIlinykhDev commented
> Кажется, ты не заметил комментарии, вот здесь, если нажать кнопку loadmore, то появятся еще комментарии, там есть про дублирование ккода, которое хочу, чтобы ты исправил <img alt="Screen Shot 2021-12-10 at 22 18 17" width="893" src="https://user-images.githubusercontent.com/32193933/145629568-2c9bbd13-4a5b-42e1-9adc-6e78dfdedb71.png">

Точно, так и есть

2021-12-13 01:06 UTC, grishbar commented
отлично, все ошибки исправил, работу принимаю, удачи в дальнейшем обучении

2021-12-13 08:20 UTC, merged